import type { ReservationSlot, Store } from "./types";

const isoHoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

const slots = (
  s18: ReservationSlot["status"],
  s19: ReservationSlot["status"],
  s20: ReservationSlot["status"],
  s21: ReservationSlot["status"],
): ReservationSlot[] => [
  { time: "18:00", status: s18 },
  { time: "19:00", status: s19 },
  { time: "20:00", status: s20 },
  { time: "21:00", status: s21 },
];

export const seedStores: Store[] = [
  {
    id: "store-001",
    name: "강의끝포차",
    area: "front_gate",
    address: "정문 앞 샘플로 12",
    category: "포차",
    capacity: {
      maxContiguousGroupSize: 6,
      maxSplitGroupSize: 10,
      capacityNote: "4~6명 소규모 테이블 중심입니다.",
    },
    seating: {
      types: ["combined_tables"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: true,
      description: "작은 테이블 2개까지 붙일 수 있어 6명 이하 모임에 적합합니다.",
    },
    status: {
      currentGroupStatus: "good",
      reservationSlots: slots("available", "available", "inquiry", "unavailable"),
      lastUpdatedAt: isoHoursAgo(2),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "phone",
      phone: "0500-0000-0001",
      messageHint: "전화 문의 시 테이블 결합 가능 여부를 확인하세요.",
    },
    notes: "뒤풀이 1차보다 가벼운 2차 모임에 적합합니다.",
  },
  {
    id: "store-002",
    name: "둥근테이블",
    area: "back_gate",
    address: "후문 골목 샘플로 7",
    category: "술집",
    capacity: {
      maxContiguousGroupSize: 8,
      maxSplitGroupSize: 12,
      capacityNote: "원형 테이블이 많아 아주 큰 단체는 분리될 수 있습니다.",
    },
    seating: {
      types: ["hall_split"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: false,
      description: "원형 테이블 중심이라 8명까지는 대화하기 편합니다.",
    },
    status: {
      currentGroupStatus: "limited",
      reservationSlots: slots("available", "inquiry", "inquiry", "unavailable"),
      lastUpdatedAt: isoHoursAgo(4),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "message",
      phone: "0500-0000-0002",
      messageHint: "원형 테이블 배치라 인원에 따라 나뉠 수 있습니다.",
    },
  },
  {
    id: "store-003",
    name: "큰마당호프",
    area: "food_street",
    address: "먹자골목 샘플길 21",
    category: "호프",
    capacity: {
      maxContiguousGroupSize: 12,
      maxSplitGroupSize: 28,
      capacityNote: "넓은 홀이 있어 분리 착석까지는 큰 단체도 가능합니다.",
    },
    seating: {
      types: ["combined_tables", "hall_split"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: true,
      description: "홀 테이블을 일부 붙일 수 있고, 20명 이상은 여러 구역으로 나뉠 가능성이 큽니다.",
    },
    status: {
      currentGroupStatus: "good",
      reservationSlots: slots("available", "available", "available", "inquiry"),
      lastUpdatedAt: isoHoursAgo(1),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "phone",
      phone: "0500-0000-0003",
      messageHint: "20명 이상은 같은 홀 내 분리 착석 가능성을 확인하세요.",
    },
    notes: "총 수용 규모는 크지만 모두 붙어 앉는 것은 제한적입니다.",
  },
  {
    id: "store-004",
    name: "조용한룸",
    area: "station",
    address: "역 앞 샘플대로 4",
    category: "이자카야",
    capacity: {
      maxContiguousGroupSize: 10,
      maxSplitGroupSize: 16,
      capacityNote: "룸 이용 가능 여부에 따라 체감 적합도가 달라집니다.",
    },
    seating: {
      types: ["private_room", "combined_tables"],
      hasPrivateRoom: true,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: true,
      description: "10명 내외 룸이 있으나 시간대별 확인이 필요합니다.",
    },
    status: {
      currentGroupStatus: "inquiry_needed",
      reservationSlots: slots("inquiry", "inquiry", "available", "inquiry"),
      lastUpdatedAt: isoHoursAgo(30),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "phone",
      phone: "0500-0000-0004",
      messageHint: "룸 사용 가능 여부를 먼저 확인하는 것이 좋습니다.",
    },
  },
  {
    id: "store-005",
    name: "반칸라운지",
    area: "food_street",
    address: "먹자골목 샘플길 33",
    category: "라운지",
    capacity: {
      maxContiguousGroupSize: 14,
      maxSplitGroupSize: 24,
      capacityNote: "반분리 구역을 확보하면 12~14명 모임에 좋습니다.",
    },
    seating: {
      types: ["semi_private_area", "combined_tables"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: true,
      tablesCanBeCombined: true,
      description: "반분리 공간과 결합 테이블을 함께 사용할 수 있습니다.",
    },
    status: {
      currentGroupStatus: "good",
      reservationSlots: slots("available", "available", "inquiry", "inquiry"),
      lastUpdatedAt: isoHoursAgo(3),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "message",
      phone: "0500-0000-0005",
      messageHint: "반분리 구역 선점 가능 시간을 확인하세요.",
    },
  },
  {
    id: "store-006",
    name: "골목분식포차",
    area: "back_gate",
    address: "후문 샘플골목 3",
    category: "분식포차",
    capacity: {
      maxContiguousGroupSize: 4,
      maxSplitGroupSize: 8,
      capacityNote: "좌석 간격이 좁아 큰 단체는 어렵습니다.",
    },
    seating: {
      types: ["hall_split"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: false,
      description: "2~4명 단위 방문에 적합한 작은 매장입니다.",
    },
    status: {
      currentGroupStatus: "difficult",
      reservationSlots: slots("unavailable", "unavailable", "inquiry", "unavailable"),
      lastUpdatedAt: isoHoursAgo(6),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "phone",
      phone: "0500-0000-0006",
    },
  },
  {
    id: "store-007",
    name: "긴테이블집",
    area: "front_gate",
    address: "정문 샘플로 40",
    category: "한식주점",
    capacity: {
      maxContiguousGroupSize: 18,
      maxSplitGroupSize: 18,
      capacityNote: "긴 테이블 하나를 확보하면 18명까지 함께 앉을 수 있습니다.",
    },
    seating: {
      types: ["long_table"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: false,
      description: "긴 테이블 중심이라 붙어 앉는 단체 모임에 강점이 있습니다.",
    },
    status: {
      currentGroupStatus: "limited",
      reservationSlots: slots("inquiry", "available", "available", "unavailable"),
      lastUpdatedAt: isoHoursAgo(8),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "phone",
      phone: "0500-0000-0007",
      messageHint: "긴 테이블 선점 여부를 확인하세요.",
    },
  },
  {
    id: "store-008",
    name: "넓은홀식당",
    area: "campus_nearby",
    address: "캠퍼스 주변 샘플길 18",
    category: "식당",
    capacity: {
      maxContiguousGroupSize: 10,
      maxSplitGroupSize: 30,
      capacityNote: "전체 수용 인원은 크지만 함께 앉기는 제한적입니다.",
    },
    seating: {
      types: ["hall_split", "combined_tables"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: true,
      description: "넓은 홀에 여러 테이블이 있어 같은 매장 내 분산 착석에 적합합니다.",
    },
    status: {
      currentGroupStatus: "good",
      reservationSlots: slots("available", "inquiry", "available", "available"),
      lastUpdatedAt: isoHoursAgo(5),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "app_request",
      phone: "0500-0000-0008",
      messageHint: "붙어 앉기보다 같은 매장 이용 가능성 중심으로 문의하세요.",
    },
  },
  {
    id: "store-009",
    name: "작은잔",
    area: "station",
    address: "역 앞 샘플골목 9",
    category: "바",
    capacity: {
      maxContiguousGroupSize: 5,
      maxSplitGroupSize: 8,
      capacityNote: "분위기형 소형 매장이라 큰 단체에는 맞지 않을 수 있습니다.",
    },
    seating: {
      types: ["hall_split"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: false,
      tablesCanBeCombined: false,
      description: "작은 테이블과 바 좌석 중심입니다.",
    },
    status: {
      currentGroupStatus: "inquiry_needed",
      reservationSlots: slots("inquiry", "unavailable", "inquiry", "available"),
      lastUpdatedAt: isoHoursAgo(26),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "message",
      phone: "0500-0000-0009",
    },
  },
  {
    id: "store-010",
    name: "후문마당",
    area: "back_gate",
    address: "후문 샘플대로 25",
    category: "고깃집",
    capacity: {
      maxContiguousGroupSize: 16,
      maxSplitGroupSize: 22,
      capacityNote: "테이블 결합이 쉬워 12~16명 모임에 강합니다.",
    },
    seating: {
      types: ["combined_tables", "semi_private_area"],
      hasPrivateRoom: false,
      hasSemiPrivateArea: true,
      tablesCanBeCombined: true,
      description: "테이블 결합과 반분리 구역을 함께 활용할 수 있습니다.",
    },
    status: {
      currentGroupStatus: "good",
      reservationSlots: slots("available", "available", "available", "inquiry"),
      lastUpdatedAt: isoHoursAgo(2),
      updateSource: "mock",
    },
    contact: {
      contactMethod: "phone",
      phone: "0500-0000-0010",
      messageHint: "고기 테이블 배치 특성상 단체 인원과 화구 수를 함께 확인하세요.",
    },
  },
];
